### PR TITLE
Solves issue #31

### PR DESCRIPTION
**Pull request by guptavarun619**
Added [New design for the homepage](https://github.com/coderwassananmol/BUB2/issues/31).

BUB2_UI

Please have a look at the UI design and share your feedback.

### CODE REVIEW

**Comment by rajat2502** [comment]
@coderwassananmol Please review the design.

**Comment by coderwassananmol** [comment]
> Added [New design for the homepage](https://github.com/coderwassananmol/BUB2/issues/31).
> 
> BUB2_UI
> 
> Please have a look at the UI design and share your feedback.

Thanks a lot for the mockup. It looks amazing. I just have a few concerns:
1. All the images that you took should fall under [Creative Commons Licenses](https://creativecommons.org/licenses/).
2. On the right side, please remove the books. Can you please show this?
screencapture-bub2-toolforge-org-2020-03-08-02_51_56. You can re-design this section.
3. The background of star and fork buttons should be the same as in "Upload".
4. The submit button is missing in the design. Please add it.

Again, thanks for the effort. Please send me a new design with these changes.

**Comment by guptavarun619** [comment]
Thanks for your feedback. I realised a lot was missing 😅. I'll get back to you after changes.

**Comment by guptavarun619** [comment]
I've revised the design according to the required changes.

BUB_UI

**Comment by ankitjena** [comment]
> I've revised the design according to the required changes.
> 
> BUB_UI

Looks amazing! Waiting for you to get this into code.

**Comment by guptavarun619** [comment]
Shall I use Material-UI for this? Since it is so popular, almost anyone working on React will be able to contribute.

**Comment by coderwassananmol** [comment]
> I've revised the design according to the required changes.
> 
> BUB_UI

Quite impressive. Approved!

**Comment by coderwassananmol** [comment]
> Shall I use Material-UI for this? Since it is so popular, almost anyone working on React will be able to contribute.

Material-UI is a great step moving forward. We can take advantage of their components. You may use it.

**Comment by guptavarun619** [comment]
Please add 'gssoc20' and difficulty level label to the PR and assign it to me.

**Pull request merged**
