### PR TITLE
favicons added

### LINKED ISSUE #87: add favicon file
design and add favicon file.

### PR DESCRIPTION
**Pull request by Xtremilicious**
Fixes #87 

Added favicons for browsers, apple devices and MS Tiles.

### CODE REVIEW

**Comment by Parikshit-Hooda** [comment]
@Xtremilicious can you deploy it using netlify so that we can see?

**Comment by Xtremilicious** [comment]
@Parikshit-Hooda for deployment on Netlify, I need to set up the .env variables, Redis and other APIs, which would need some extra work. 

I think the code I added should work correctly, it justs affects the header. 
If @coderwassananmol insists, then I can try deploying it.

**Comment by Parikshit-Hooda** [comment]
I suppose there is no need. it would have been great though, if one could visually verify it.

**Comment by Xtremilicious** [comment]
Automatic Netlify previews can be setup with an integration with this repo. This way whenever a PR is raised, Netlify creates a deploy preview automatically. This would be really good for verifying the PRs and the PR creator doesn’t have to deploy it himself:)

Kindly check out this feature.

**Comment by Parikshit-Hooda** [comment]
@rkpattnaik780 please review.

**Comment by rkpattnaik780** [comment]
This seems to be working fine in my system. I have some doubts though, how exactly is the current code using `safari-pinned-tab.svg`. Is `site.webmanifest` really being used?

**Comment by Xtremilicious** [comment]
@rkpattnaik780 the `safari-pinned-tab.svg` can be used for the Safari Pinned Tab feature as described here: http://markhagethorn.com/2015/11/23/apple_pinned_tab.html

 Details about the web manifest can be found here: https://web.dev/add-manifest

I did not add these directly in the code but exported the required files for the provision to later add these if needed.

**Comment by rkpattnaik780** [comment]
@Parikshit-Hooda @Xtremilicious since BUB2 Is not a PWA, I don't think we should go with the current implementation. Only a `favicon.ico` should suffice. Any opinions?

**Comment by Xtremilicious** [comment]
Sure, I’ll remove the unused files and commit again👍

**Comment by Xtremilicious** [comment]
@rkpattnaik780 I removed them :)

**Comment by Xtremilicious** [comment]
@rkpattnaik780 @Parikshit-Hooda @coderwassananmol Kindly review and merge :)

**Comment by Xtremilicious** [comment]
Welcome @coderwassananmol :)

**Comment by Xtremilicious** [comment]
@rkpattnaik780 @Parikshit-Hooda @coderwassananmol Kindly assign the appropriate labels for the points to be updated.

**Pull request merged**
