### PR TITLE
updated stats page UI

### PR DESCRIPTION
**Pull request by BhuwanChandra**
feat: Change the UI according to the new design

Capture

fixes: #78 stats page

### CODE REVIEW

**Comment by coderwassananmol** [comment]
Thanks for the PR, @BhuwanChandra! I reviewed your code and there might be some issues regarding responsiveness. Can you please make some changes so that the new design adapts to different screen sizes?

**Comment by BhuwanChandra** [comment]
@coderwassananmol improved responsiveness for lg, md, sm and xs devices.

Capture2

Capture1

**Comment by coderwassananmol** [comment]
Thanks!

**Comment by ankitjena** [comment]
@BhuwanChandra Please resolve the conflicts and we can merge

**Comment by BhuwanChandra** [comment]
@ankitjena conflicts resolved.

**Pull request merged**
