### PR TITLE
Redesigned Home page

### LINKED ISSUE #78: Change the UI according to the new design
A .fig file resides insides public folder. New UI has to be made in accordance with that.

### PR DESCRIPTION
**Pull request by Xtremilicious**
Fixes #78 

ScreenShot_20200326174101

@coderwassananmol @ankitjena @Parikshit-Hooda Kindly have a look :)

### CODE REVIEW

**Comment by rajat2502** [comment]
LGTM

**Comment by Parikshit-Hooda** [comment]
goes without saying that we should pull it on local and check it. @coderwassananmol @rkpattnaik780 @rajat2502

**Comment by coderwassananmol** [comment]
Thanks for the PR!
Here are my comments:
1. Please use internal styling (<style jsx>) to style components.
2. We can get rid of the content just below the header since that content is now available in the right side of the upload.
3. The size of the input has to be large. Just like in the approved design:
https://user-images.githubusercontent.com/45912180/76157233-10691980-612c-11ea-8579-1440265a0ae5.png
4. The container should have no padding from the header and footer.
5. Some components get messed up when I test it on mobile. Please fix them as well.

**Comment by Xtremilicious** [comment]
Thanks for the comments. 

Instructions for the comments:
1. Did try it, was running into problems, due to the problems caused by the layout of the original component. It would be a lot of work to re-do the component from scratch. Will try it again though.
2. This portion belongs to the Header component, I believe this part is assigned to someone else.
3. Will work on it :)
4. Same as 2.
5. Will work on it :)

**Comment by Xtremilicious** [comment]
@coderwassananmol kindly check my comments. Thanks :)

**Comment by coderwassananmol** [comment]
> Thanks for the comments.
> 
> Instructions for the comments:
> 
> 1. Did try it, was running into problems, due to the problems caused by the layout of the original component. It would be a lot of work to re-do the component from scratch. Will try it again though.
> 2. This portion belongs to the Header component, I believe this part is assigned to someone else.
> 3. Will work on it :)
> 4. Same as 2.
> 5. Will work on it :) Kindly share screenshots. It worked okay for me though.

I can help you out if you need some help in styling. No need to worry. The 2nd point is not under the header component. It comes under the main component. I have attached the screenshot and left some comments in "RED". Please go through them as well.
Screenshot 2020-03-27 at 4 54 38 AM

**Comment by Xtremilicious** [comment]
@coderwassananmol @rajat2502 @Parikshit-Hooda I have fixed all the problems.

ScreenShot_20200327130455
As I mentioned before, the comments No. 2 and 4 did belong to the respective Header and Footer components.

But I fixed them anyway :)

Kindly review and merge.

**Comment by Xtremilicious** [comment]
@rkpattnaik780 In what resolution are the screenshots taken?

This is how it looks in my system:
(Laptop):
ScreenShot_20200327165114

(Mobile):
ScreenShot_20200327165125

**Comment by Xtremilicious** [comment]
@rkpattnaik780 Fixed the non-uniformly dark problem.

But I can't reproduce the problem in the screenshot where the downward arrow is misplaced. Kindly see the screenshots I sent.

**Comment by rkpattnaik780** [comment]
The dark border looks fine now. Have you checked it in firefox ( for misplaced down arrow) ?

**Comment by Xtremilicious** [comment]
> The dark border looks fine now. Have you checked it in firefox ( for misplaced down arrow) ?

Yep, I checked it on Chrome, Firefox as well as Opera. Looks fine to me.

**Comment by rkpattnaik780** [comment]
> > The dark border looks fine now. Have you checked it in firefox ( for misplaced down arrow) ?
> 
> Yep, I checked it on Chrome, Firefox as well as Opera. Looks fine to me.

My resolution is 1920 X 1080

**Comment by Xtremilicious** [comment]
> > > The dark border looks fine now. Have you checked it in firefox ( for misplaced down arrow) ?
> > 
> > 
> > Yep, I checked it on Chrome, Firefox as well as Opera. Looks fine to me.
> 
> My resolution is 1920 X 1080

Yep, checked it on 1920x1080. Make sure your zoom is 100%(default: no zoom)
ScreenShot_20200327170751

**Comment by rkpattnaik780** [comment]
> > > > The dark border looks fine now. Have you checked it in firefox ( for misplaced down arrow) ?
> > > 
> > > 
> > > Yep, I checked it on Chrome, Firefox as well as Opera. Looks fine to me.
> > 
> > 
> > My resolution is 1920 X 1080
> 
> Yep, checked it on 1920x1080. Make sure your zoom is 100%(default: no zoom)
> ScreenShot_20200327170751

Zoom is 100% only

**Comment by Xtremilicious** [comment]
> > > > > The dark border looks fine now. Have you checked it in firefox ( for misplaced down arrow) ?
> > > > 
> > > > 
> > > > Yep, I checked it on Chrome, Firefox as well as Opera. Looks fine to me.
> > > 
> > > 
> > > My resolution is 1920 X 1080
> > 
> > 
> > Yep, checked it on 1920x1080. Make sure your zoom is 100%(default: no zoom)
> > ScreenShot_20200327170751
> 
> Zoom is 100% only

Oh, let's see what the others have to say @Parikshit-Hooda @coderwassananmol @rajat2502

**Comment by coderwassananmol** [comment]
Screenshot 2020-03-27 at 7 57 24 PM
@Xtremilicious Even on my screen, the arrow is messed up.

**Comment by Xtremilicious** [comment]
@coderwassananmol The problem I think is due to the absolute positioning of the arrow. The only way to solve it is to use the original arrow that comes with the <select> tag. 

Using absolute positioning doesn't work on all devices, as I see in this case.

What should I do regarding the arrow? Note that the only way to customize the arrow is by absolute positioning it inside the select box.

**Comment by Xtremilicious** [comment]
@coderwassananmol Kindly check now, pushed some fixes for your specified resolution range.

**Comment by rkpattnaik780** [comment]
Current view in Firefox, the down arrow is still distoreted, and dark borders are inconsistent 

Screenshot from 2020-03-27 23-06-29

**Comment by Xtremilicious** [comment]
@rkpattnaik780 Fixed it, kindly check,

**Comment by coderwassananmol** [comment]
@Xtremilicious The design still looks somewhat messy. It is still breaking on my system. Let's not waste time reinventing the wheel. I will anyway integrate Material UI components, let's start with them already. For the three fields and submit button, use the material UI components.

**Comment by Xtremilicious** [comment]
@coderwassananmol Could have saved me much time if you had told me before, hehe. Custom designing the floating texts took a lot of time :(

**Comment by Xtremilicious** [comment]
@coderwassananmol I'm closing this. Kindly assign it to someone else. Thank you :)

**Comment by coderwassananmol** [comment]
Let's consider your effort and time in building this. I will merge your PR. The material UI component will be taken as an enhancement later on in the future.
Thanks!

**Comment by Xtremilicious** [comment]
@coderwassananmol Thanks a lot! I'll be sure to apply for the enhancement :)

**Comment by Xtremilicious** [comment]
Kindly assign the appropriate labels @coderwassananmol

**Pull request merged**
