### PR TITLE
Solves issue: #79

### PR DESCRIPTION
**Pull request by guptavarun619**
Added [wireframe for /stats Page](https://github.com/coderwassananmol/BUB2/issues/79)

Stats Page

- I've added the job/process in the queue(as it'll be more descriptive to the user).
- Instead of only showing the number of books, we can show the cover of latest books on Internet Archive(suggestion).

Please review this PR, add 'gssoc20' and 'difficulty level' label to the PR and assign it to me.

### CODE REVIEW

**Comment by guptavarun619** [comment]
Shall I put the **Number of Books on Interner Archive : XY** in huge font size? Otherwise, a lot of space would be wasted without any pattern or symmetry

**Comment by Parikshit-Hooda** [comment]
@guptavarun619 putting the number of books on internet archive stat is not required, right now. There are two reasons, it would make the site make frequent calls to retrieve the current number, which isn't required rn. Second, we can extend the books uploaded columns more downward(also add scrolls to show that the section is scrollable) to avoid the (possible)annoyance of scrolling too much. @rkpattnaik780 your comments, please.

**Comment by guptavarun619** [comment]
Here are the changes I've done according to what @Parikshit-Hooda guided. Please review it, below is the Screenshot. Thank you for your valuable time.

Stats Page

**Comment by Parikshit-Hooda** [comment]
@rkpattnaik780 Please see to this. LGTM.

**Pull request merged**
