### PR TITLE
Added index.html,queue.html and style.css

### LINKED ISSUE #66: Improve  the Responsiveness of the website https://bub2.toolforge.org/
1. Correct the position of the Enter E-mail input field under the Upload Tab

2. Correct the position of the Card Section under the Queues Tab.

Please assign me this task

### PR DESCRIPTION
**Pull request by CSElonewolf**
closes #66 

Added index.html,queue.html and style.css .

The upload page is here :--
Screenshot_2020-03-08-14-28-54-184_com android browser

The queue page is here :---
Screenshot_2020-03-08-14-28-30-512_com android browser

### CODE REVIEW

**Comment by Parikshit-Hooda** [comment]
@ankitjena Please review this.

**Comment by CSElonewolf** [comment]
@ankitjena I had reported my problem with REACT already .You can follow this [Comment Thread](https://github.com/coderwassananmol/BUB2/issues/66#issuecomment-596072531) .
But @coderwassananmol gave a green signal with this [Comment Thread](https://github.com/coderwassananmol/BUB2/issues/66#issuecomment-596139429).
Therefore I moved forward.But its Ok.You can unassign me and close the PR.

**Comment by ankitjena** [comment]
@CSELoneWolf React is pretty easy to learn, you should not have a problem with react. Plus @coderanmolwassan said so because page responsiveness depends on CSS not the frontend framework.

**Comment by ankitjena** [comment]
@CSElonewolf Any updates?

**Comment by CSElonewolf** [comment]
No sir,I am currently not working on it.

**Comment by coderwassananmol** [comment]
@ankitjena Why was this PR closed?

**Comment by ankitjena** [comment]
@coderwassananmol Since the participant was no longer working on the PR.

**Comment by coderwassananmol** [comment]
@CSElonewolf You can use styled jsx inside react code. See this: https://github.com/coderwassananmol/BUB2/blob/develop/pages/stats.js#L19
This way, you can style your components just using normal CSS.
I am reopening this PR to give you another chance since you worked on it earlier. :)

**Comment by Parikshit-Hooda** [comment]
@ankitjena Please review.

**Comment by coderwassananmol** [comment]
Closing the PR due to inactivity.

**Pull request closed without merging**
