### PR TITLE
update issue templates

### PR DESCRIPTION
**Pull request by ishukhanchi**

### CODE REVIEW

**Comment by Parikshit-Hooda** [comment]
@rkpattnaik780 please review.

**Comment by Parikshit-Hooda** [comment]
Also, remove ISSUE_TEMPLATE directory from the repo root. It should be considered moved from project root to '.github' directory.

**Comment by ishukhanchi** [comment]
> Also, remove ISSUE_TEMPLATE directory from the repo root. It should be considered moved from project root to '.github' direct

**Comment by ishukhanchi** [comment]
Removed ISSUE_TEMPLATE directory from repo root.

**Pull request merged**
