### PR TITLE
Fixes:[T344116] Fix peer dependencies and remove deprecation warnings

### PR DESCRIPTION
**Pull request by okerekechinweotito**
Fixes: [T344116](https://phabricator.wikimedia.org/T344116)

## Proposed Changes
- Fixing the peer dependencies while doing npm install
- Removing as much deprecation warnings as possible
- Update dependencies in package.json and fix related code

## Files Created/Updated

- components/QueueSection.js - remove unused imports
- componentsQueueTable.js - update material-UI code to version 5
- components/ShowJobInformation - update material-UI code to version 5
- package.json - Update material-UI , update bull , update react and react-dom , remove querystring as it is unused

## SETUP / RESULTS
- Delete .next folder
- Delete node_modules
- Delete package-lock.json
- Run-  npm cache clean --force
- Run-  npm install
Able to run npm install without dependency conflicts

**PENDING DEPRECATION**
har-validator and uuid are peer dependencies of the request package which has been deprecated
request-promise extends the now deprecated request package

NOTE: I decided not to remove/update the request and request-promise as it would require a significant change across the codebase. The changes could be done incrementally

## Checklist 
- [x] Coding Conventions are followed.
- [x] Comments are used for Documenting the Code.
- [x] Correct File Names are mentioned.

### CODE REVIEW

**Comment by Parthiv-M** [comment]
Which node/npm version have you used while resolving conflicts?

**Comment by okerekechinweotito** [comment]
@Parthiv-M 

node - v18.17.1
npm - 9.6.7

**Comment by coderwassananmol** [comment]
anmol@Anmol-MacBook-Air BUB2 % npm install             
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR! 
npm ERR! While resolving: BUB2@1.0.0
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   react@"^17.0.2" from the root project
npm ERR!   peer react@"^16.8.0 || ^17.0.0" from @material-ui/core@4.12.4
npm ERR!   node_modules/@material-ui/core
npm ERR!   13 more (@material-ui/styles, @material-ui/system, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! @mui/material@"^5.14.12" from the root project
npm ERR! 
npm ERR! Conflicting peer dependency: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peer react@"^17.0.0 || ^18.0.0" from @mui/material@5.14.13
npm ERR!   node_modules/@mui/material
npm ERR!     @mui/material@"^5.14.12" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/anmol/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/anmol/.npm/_logs/2023-10-16T19_15_48_507Z-debug-0.log

@okerekechinweotito I got the following errors with npm version 8.11.0 and node version v16.16.0. Ideally, these versions should be supported. I removed node_modules and tried but still got the same error.

**Comment by okerekechinweotito** [comment]
@coderwassananmol 
Please in addition to removing node_modules , also 
- delete .next folder
- delete package-lock.json
- Run -  npm cache clean --force
- then run - npm install
I tried this with your npm version 8.11.0 and node version v16.16.0. and it installed

**Comment by coderwassananmol** [comment]
Thanks @okerekechinweotito

**Pull request merged**
