### PR TITLE
Bub2 redesign fa qs page

### PR DESCRIPTION
**Pull request by Ed-Gah**
## Files Modified
`components/Header.js`
`utils/constants.js`

## Files Added
`components/FaqsSection.js`
`pages/faqs.js`

## Results
Screenshot from 2023-10-05 10-28-29

### CODE REVIEW

**Review by coderwassananmol — CHANGES_REQUESTED** [review]
Screenshot 2023-10-13 at 1 03 18 AM
@Ed-Gah There's a white space in the footer. Please remove it and resubmit the PR.

**Comment by Ed-Gah** [comment]
Sir @coderwassananmol the white space in the footer has been removed.
Screenshot from 2023-10-13 03-18-39

**Review by coderwassananmol — CHANGES_REQUESTED** [review]
Screenshot 2023-10-19 at 12 09 15 AM
Screenshot 2023-10-19 at 12 09 21 AM

@Ed-Gah Upload page still has white space. The footer is getting cut. The footer should be fixed at the bottom and completely visible. The page should also not be scrollable.

**Comment by coderwassananmol** [comment]
@Ed-Gah The table is getting cut in the Queue Page
Screenshot 2023-10-20 at 12 50 54 AM

If it helps, you can add the scroll to Queue Page or remove "Search Book" heading as the search bar is itself self-explanatory.

**Comment by Ed-Gah** [comment]
Sir @coderwassananmol 

I have removed the "Search Book" heading

**Review by coderwassananmol — APPROVED** [review]

**Pull request merged**
