### PR TITLE
created design for book preview component

### PR DESCRIPTION
**Pull request by BhuwanChandra**
fixes: #122 

Book Preview

### CODE REVIEW

**Comment by ankitjena** [comment]
@coderwassananmol @rkpattnaik780 Will it be better to have a modal component instead of a separate page?

**Comment by rkpattnaik780** [comment]
> @coderwassananmol @rkpattnaik780 Will it be better to have a modal component instead of a separate page?

I think so too. A whole different page for the preview seems unnecessary and won't make for a good UX.

**Comment by BhuwanChandra** [comment]
@ankitjena @rkpattnaik780 do I need to include modal window design or separate page design?

Book Preview modal

**Comment by coderwassananmol** [comment]
> @ankitjena @rkpattnaik780 do I need to include modal window design or separate page design?
> 
> Book Preview modal

Hi @BhuwanChandra , we only require the modal component on top of the Home page.

**Comment by rkpattnaik780** [comment]
@ankitjena . I feel the `Cancel` and `Upload` buttons are not suitable for this one. We can have something like `Continue` maybe. I am not sure.

**Comment by coderwassananmol** [comment]
Let's have 2 buttons:
"Cancel" and "Continue with upload"
@BhuwanChandra 

@ankitjena @rkpattnaik780 Please note.

**Comment by BhuwanChandra** [comment]
@coderwassananmol in "Continue with upload", button size will be too large. I think "Continue" will be better.

**Comment by coderwassananmol** [comment]
> @coderwassananmol in "Continue with upload", button size will be too large. I think "Continue" will be better.

No issues. We can reduce the size of the text or split the text in two.

**Comment by BhuwanChandra** [comment]
@coderwassananmol I have changed the buttons and also changed their colours, previous colours were looking out of theme of the website. 

Book Preview

**Comment by coderwassananmol** [comment]
LGTM.

**Comment by BhuwanChandra** [comment]
@coderwassananmol @rkpattnaik780 please add related tags on this PR.

**Pull request merged**
