### PR TITLE
[WIP] Fixes: T315134

### PR DESCRIPTION
**Pull request by varun-s22**
Adds input search bar to the queue page

## Files Updated
* pages/_app.js (for adding new styles)
* pages/queue.js (for adding search-input field)

## Here how it looks currently
Screenshot 2023-08-16 at 03 00 37

### CODE REVIEW

**Comment by coderwassananmol** [comment]
@varun-s22 Here are my thoughts:
1) We don't need the user to click on search. The search can happen as the user types. It can be based on job id and title. Please keep the placeholder as "Search by job id or title"
2) You can refer to [Typeahead Search](https://doc.wikimedia.org/codex/latest/components/demos/typeahead-search.html#css-only-version) for reference. We can skip the "Search" button as the search will happen automatically.
3) I would suggest we keep the search bar on top of the table so that the context is given to the user that search is for the table.

**Comment by varun-s22** [comment]
hey @coderwassananmol 

1. Done
2. Lets discuss more about this, do we want "live autocomplete" feature, where you type somewhat incomplete title or id, and it autocompletes, or do we want to type the entire stuff up, and then match the results. I would prefer the first one, as we don't have a dedicated Search button, so it makes sense to add autocomplete to the search bar.
3. We have two choices

### Choice 1
Screenshot 2023-08-17 at 01 59 55
Here the length of the search bar expands till the table width

### Choice 2
Screenshot 2023-08-17 at 02 00 11
Here the length of search bar matches the length of "Select a Queue" option


I would personally prefer **Choice 2**, as it maintains the consistency from above.

**Comment by varun-s22** [comment]
also how would i add some data to my QueueTable.js, as currently its empty, so I can't test the search feature :(

**Comment by Parthiv-M** [comment]
> also how would i add some data to my QueueTable.js, as currently its empty, so I can't test the search feature :(

You can just try uploading a book using any one of the available libraries (Google Books, PDL or Trove). The data will reflect on the table, assuming you have Redis set up :)

**Comment by varun-s22** [comment]
> > also how would i add some data to my QueueTable.js, as currently its empty, so I can't test the search feature :(
> 
> You can just try uploading a book using any one of the available libraries (Google Books, PDL or Trove). The data will reflect on the table, assuming you have Redis set up :)

yeah for that i need to have the wiki keys right? ( for logging in via wikimedia), and i dont know what perms to tick for getting those
can u share the steps for generating those keys?

**Comment by coderwassananmol** [comment]
@varun-s22 You can request a key from [Beta Wiki](https://meta.wikimedia.beta.wmflabs.org/wiki/Special:OAuthConsumerRegistration) For reference, check this [proposal](https://meta.wikimedia.beta.wmflabs.org/wiki/Special:OAuthListConsumers/view/e70de440468d7140914e4a57e3660cf2). Once you've the keys and they are approved, you need to change the authorization, you need to change the `token`, `userInfo`, `authorization` in the `[..nextAuth].js`. Refer [this](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/wikimedia.ts#L170-L174) for more details. Change the domain from https://meta.wikimedia.org to https://meta.wikimedia.beta.wmflabs.org/ and it should work.

Choice 1 looks good to me and we should only filter the Queue table. No need to show suggestions. Can you also remove Search a Book heading since the search bar should be self-explanatory.

**Comment by Parthiv-M** [comment]
Closing this as it is fixed in #180

**Pull request closed without merging**
