### PR TITLE
Added MIT License

### PR DESCRIPTION
**Pull request by andrewyavors**

### CODE REVIEW

**Comment by coderwassananmol** [comment]
Hi @andrewyavors, the PR looks good. Can you add a few lines after the LICENSE heading in README.md? Something like "We follow MIT license.....etc."

**Comment by andrewyavors** [comment]
Done

**Comment by coderwassananmol** [comment]
Hi @andrewyavors, since @even4void made the PR first, I have to consider his PR first. You may take up any other open issue. Thanks for your contribution!

**Comment by even4void** [comment]
Sorry about that, Andrew. I didn't notice you were on the same track when I submitted my PR. Cheers,

**Pull request closed without merging**
