### PR TITLE
Added pre-commit hooks

### LINKED ISSUE #106: Configure husky to lint staged changes.
Currently there are no pre-commit hooks to pretify the code. It will be good if the project can have a `husky` and `prettier` configured such that the staged files will get prettified before being commited.

### PR DESCRIPTION
**Pull request by jamesjose03**
Fixes #106 
- Added `prettier` and `husky` as pre-commit hooks.
- Tested on server.js file.

### CODE REVIEW

**Comment by jamesjose03** [comment]
cc @Parikshit-Hooda @rkpattnaik780 Pls review this PR.

**Comment by Parikshit-Hooda** [comment]
I am getting a compile error in books.js line 411

 ./components/Books.js
SyntaxError: E:\bub2\BUB2\components\Books.js: Unexpected token (411:25)

```
  409 |                     required className = "form-control"
  410 |                     id = "bookid"
 411 |                     aria - describedby = "bid" /
      |                          ^
  412 |                     >
  413 |                     <
  414 |                     div className = "input-group-btn" >
```

**Comment by rkpattnaik780** [comment]
@Parikshit-Hooda , it is working fine. I can't see any compilation error.

**Comment by jamesjose03** [comment]
@Parikshit-Hooda It's not showing any error for me too.

**Comment by Parikshit-Hooda** [comment]
Is this error not appearing on your locals?
Lemme check again.
Update: I just checked and it persists.

**Comment by Parikshit-Hooda** [comment]
I must have made a bad pull. I have just removed my review assignment.

**Comment by Parikshit-Hooda** [comment]
@jamesjose03 we have a conflict in server.js . Please resolve it, then I will approve and merge.

**Comment by jamesjose03** [comment]
@Parikshit-Hooda The conflict has been resolved.

**Comment by Parikshit-Hooda** [comment]
@jamesjose03 Good word! Would you like to try the pinned issues now? They are pretty cool.

**Comment by jamesjose03** [comment]
@Parikshit-Hooda Thank you! Will try soon.

**Pull request merged**
