### PR TITLE
Fix issue #119 (Fetch basic details of the book before uploading Google Books)

### PR DESCRIPTION
**Pull request by IuliaElizaS**
Validates Google book Id while fetching book details
my solution to fix issue #119 https://github.com/coderwassananmol/BUB2/issues/119

I apologize for all the added parentheses and commas in the rest of the code. I didn't do them.  They just appeared after I pushed the commit to the repo, like the code being automatically linted

### CODE REVIEW

**Comment by rajat2502** [comment]
@coderwassananmol Please review.

**Comment by coderwassananmol** [comment]
Hi @IuliaElizaS I am facing error while trying to preview. Please fix this.
Screenshot 2020-04-22 at 7 52 55 PM

**Comment by IuliaElizaS** [comment]
Ok, I'll work on it tomorrow as soon as I have a little time.

**Comment by coderwassananmol** [comment]
@IuliaElizaS Currently, you are fetching the details during onChange event. I want this to happen when user clicks on submit. This is how the flow would work:
`User enters GB ID` > `User clicks on submit` > `Validation checks take place (checking for public domain)` > `Show preview` > `User enters the final URL` > `User clicks on submit` > `Uploading starts.` 
Also, we are already fetching the details of the book at "/check" API. I don't want multiple API calls. This should be achieved in a single API call. We can store the API response and use it later. 

Let me know if you need some help in implementing the same.

**Comment by IuliaElizaS** [comment]
@coderwassananmol ok, please tell me, during the validation, do you want to check only if the book belongs to the public domain (if it's free)? or also if the entered link is correct?
Should I also work on showing the preview? ... I know it's another issue opened for this (#120) ... and these 2 issues are connected. Thank you

**Comment by coderwassananmol** [comment]
> @coderwassananmol ok, please tell me, during the validation, do you want to check only if the book belongs to the public domain (if it's free)? or also if the entered link is correct?
> Should I also work on showing the preview? ... I know it's another issue opened for this (#120) ... and these 2 issues are connected. Thank you

Sure. Sounds good. Let us add a check for valid URI as well. If you are willing to work on #120, just comment on the issue and I will assign it to you.

**Comment by coderwassananmol** [comment]
Just submit a single PR referencing both issues. Good luck! :)

**Pull request closed without merging**
