### PR TITLE
Fix CONTRIBUTING.MD

### PR DESCRIPTION
**Pull request by akankshat05**
Resolved the merge conflict in CONTRIBUTING.MD file.
Issue - [T344122](https://phabricator.wikimedia.org/T344122)

### CODE REVIEW

**Comment by coderwassananmol** [comment]
@akankshat05 The CONTRIBUTING.md should contain the updated instructions on the following:
1. Where to find issues and new tasks (mention about Phabricator)?
2. How to raise a pull request (mention about linking Phabricator ticket in the description)
3. The PR must be reviewed by at least 1 person before it gets merged.

**Comment by akankshat05** [comment]
> Owner
I have made the requested changes. Please review them.

**Review by Parthiv-M — COMMENTED** [review]
Could you also mention that once the Pull Request is opened, it should be linked as a comment on the corresponding Phabricator task? ([like here](https://phabricator.wikimedia.org/T344119))

**Comment by akankshat05** [comment]
> Could you also mention that once the Pull Request is opened, it should be linked as a comment on the corresponding Phabricator task? ([like here](https://phabricator.wikimedia.org/T344119))

I have mentioned it. Please review.

**Comment by coderwassananmol** [comment]
LGTM

**Pull request merged**
