### PR TITLE
Create GSSOC_INSTRUCTIONS.md

### PR DESCRIPTION
**Pull request by kichloo**
Lists the instructions to be followed by the users to contribute to GSSOC.

### CODE REVIEW

**Comment by kichloo** [comment]
Fixed #54

**Comment by rkpattnaik780** [comment]
The issue was to `Add 'instructions for gssoc' section in README.md`. No need for a new markdown file. The instructions should also mention about `CONTRIBUTING.md`.

**Comment by kichloo** [comment]
@rkpattnaik780 I was told by @Parikshit-Hooda to make a different file.

**Comment by rkpattnaik780** [comment]
> @rkpattnaik780 I was told by @Parikshit-Hooda to make a different file.

Sorry I didn't go through the complete thread. The issue description asked for edits in README so I thought so.

**Comment by kichloo** [comment]
@Parikshit-Hooda I am a beginner. What and how to do?

**Comment by Parikshit-Hooda** [comment]
simple add that point in the instructions, and commit it and raise a PR.

**Comment by kichloo** [comment]
@Parikshit-Hooda Thanks for the comment. Done!

**Comment by kichloo** [comment]
@Parikshit-Hooda Can I take more issues now?

**Comment by Parikshit-Hooda** [comment]
yes.

**Pull request merged**
